name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Futureplots-${{ env.PROJECT_VERSION }}
          path: target/Futureplots-${{ env.PROJECT_VERSION }}.jar
